version: 2.1

# on:
  # push:
  #   branches:
  #     - main
  # pull_request:
  #   branches:
  #     - main

orbs:
  node: circleci/node@5.1.0
  # heroku: circleci/heroku@1.2.6

jobs: 
  prepare_env:
    executor: node/default
    working_directory: ~/project
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - persist_to_workspace:
        root: ~/project
        paths:
          - .

  build:
    executor: node/default
    working_directory: ~/project
      - run:
          command: npm run build
          name: Build app
      - persist_to_workspace:
        root: ~/project
        paths:
          - .

  unit_and_integration_tests:
    executor: node/default
    working_directory: ~/project
    - run:
        name: Run tests
        command: npm run test
    - persist_to_workspace:
        root: ~/project
        paths:
          - .

  # deploy:
  #   executor: heroku/default
  #   steps:
  #     - attach_workspace:
  #       at: ~ /project
  #     - heroku/deploy-via-git:
  #         force: true    #   force push when pushing to the heroku remote, see: https://devcenter.heroku.com/articles/git


  workflows:
    build_and_test:
      jobs: 
        - prepare_env
        - build
            requires:
              - prepare_env
        - unit_and_integration_tests
          requires: 
            - build