version: 2.1

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

orbs:
  node: circleci/node@7.1.0
  android: circleci/android@3.1.0
  # heroku: circleci/heroku@1.2.6

jobs:
  Install packages:
    executor: node/default
    working_directory: ~/workspace/repo
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - persist_to_workspace:
          root: ~/workspace
          paths:
            - .

  Unit tests:
    executor: node/default
    working_directory: ~/workspace/repo
    steps:
      - attach_workspace:
          at: ~/workspace
      - run:
          name: Run tests
          command: npm run test:unit
      - store_artifacts:
          path: jest-results.json
          destination: test-results
      - persist_to_workspace:
          root: ~/workspace
          paths:
            - .

  Build for E2E:
    executor:
      name: android/android_machine
      resource_class: large
      tag: default
    working_directory: ~/workspace
    steps:
      - attach_workspace:
          at: .
      - restore_cache:
          keys:
            - gradle-cache-v1-{{ checksum "build.gradle" }}
      - android/create_avd:
          avd_name: CI_EMULATOR
          install: true
          system_image: system-images;android-31;default;x86_64
      - run:
        name: Install EAS CLI
        command: npm install -g eas-cli
      - run:
          working_directory: ~/workspace/repo
          command: npm run build:android
          name: Build app
      - android/save_gradle_cache:
          cache_prefix: gradle-cache-v1
      - persist_to_workspace:
          root: ~/workspace
          paths:
            - .

  E2E tests:
    executor:
      name: android/android_machine
      resource_class: large
      tag: default
    working_directory: ~/workspace/repo
    steps:
      - attach_workspace:
          at: ~/workspace
      - android/create_avd:
          avd_name: CI_EMULATOR
          install: true
          system_image: system-images;android-31;default;x86_64
      - android/start_emulator:
          avd_name: CI_EMULATOR
          no_window: true
          restore_gradle_cache_prefix: v1a
      - run:
          name: Install app in Android Emulator
          command: npm run install:android
      - run:
          name: Run E2E tests
          command: npm run test:e2e-android
      - android/save_gradle_cache:
          cache_prefix: v1a
      - persist_to_workspace:
          root: ~/workspace
          paths:
            - .

  #  Build with EAS:
  #    docker:
  #      - image: cimg/node:lts
  #    working_directory: ~/workspace/repo
  #    steps:
  #      - attach_workspace:
  #          at: ~/workspace
  #      - checkout
  #      - run:
  #          name: Install dependencies
  #          command: npm ci
  #      - run:
  #          name: Build EAS
  #          command: npx eas-cli build -p android --non-interactive --local -e test
  #      - persist_to_workspace:
  #          root: ~/workspace
  #          paths:
  #            - .
  #  # deploy:
  #   executor: heroku/default
  #   steps:
  #     - attach_workspace:
  #       at: ~ /project
  #     - heroku/deploy-via-git:
  #         force: true    #   force push when pushing to the heroku remote, see: https://devcenter.heroku.com/articles/git


workflows:
  Test Android:
    jobs:
      - Install packages
      - Unit tests:
          requires:
            - Install packages
      - Build for E2E:
          requires:
            - Install packages
      - E2E tests:
          requires:
            - Build for E2E
      #      - Build with EAS
