version: 2.1

# on:
  # push:
  #   branches:
  #     - main
  # pull_request:
  #   branches:
  #     - main

orbs:
  node: circleci/node@5.1.0
  # heroku: circleci/heroku@1.2.6

jobs: 
  prepare_env:
    executor: node/default
    working_directory: ~/project
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
          
      - run:
          name:  Debug workspace
          command: pwd && ls
      - persist_to_workspace:
          root: .
          paths:
            - .

  build:
    executor: node/default
    working_directory: ~/project
    steps:
      - run:
          command: pwd && ls && npm run build
          name: Build app
      - persist_to_workspace:
          root: .
          paths:
            - .

  unit and integration tests:
    executor: node/default
    working_directory: ~/project
    steps:
      - run:
          name: Run tests
          command: npm run test
      - persist_to_workspace:
          root: .
          paths:
            - .

  # deploy:
  #   executor: heroku/default
  #   steps:
  #     - attach_workspace:
  #       at: ~ /project
  #     - heroku/deploy-via-git:
  #         force: true    #   force push when pushing to the heroku remote, see: https://devcenter.heroku.com/articles/git


workflows:
  build and test:
    jobs: 
      - prepare_env
      - build:
          requires:
            - prepare_env
      - unit and integration tests:
          requires: 
            - build


