version: 2.1

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

orbs:
  node: circleci/node@7.1.0

jobs:
  Install packages:
    executor: node/default
    working_directory: ~/workspace/repo
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
          override-ci-command: npm install --include=dev
      - persist_to_workspace:
          root: ~/workspace
          paths:
            - .

  Unit tests:
    executor: node/default
    working_directory: ~/workspace/repo
    steps:
      - attach_workspace:
          at: ~/workspace
      - run:
          name: Run tests
          command: npm run test:unit-coverage
      - store_artifacts:
          path: jest-results.json
          destination: test-results

  E2E tests:
    executor: node/default
    working_directory: ~/workspace/repo
    steps:
      - attach_workspace:
          at: ~/workspace
      - run:
          name: Install EAS CLI
          command: npm install -g eas-cli
      - run:
          name: Trigger EAS Build with Maestro Config
          no_output_timeout: 40m
          command: eas build --profile build-and-maestro-test --platform android

workflows:
  Test Android:
    jobs:
      - Install packages
      - Unit tests:
          requires:
            - Install packages
      - E2E tests:
          requires:
            - Install packages
