name: ✨ Feature Request
description: Suggest a new feature or improvement for Recipedia
title: "[FEATURE]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please fill out this form as completely as possible.
        
  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-flight checklist
      description: Please ensure you've completed these steps before submitting your feature request
      options:
        - label: I have searched the existing issues for this feature request
          required: true
        - label: I have checked that this feature doesn't already exist in the latest version
          required: true

  - type: textarea
    id: problem-description
    attributes:
      label: Problem Description
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution-description
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: I would like to see...
    validations:
      required: true

  - type: dropdown
    id: feature-category
    attributes:
      label: Feature Category
      description: What category does this feature belong to?
      options:
        - Recipe Management (add, edit, delete recipes)
        - Search & Filtering (finding recipes)  
        - Shopping List (ingredient management)
        - OCR & Camera (recipe scanning)
        - UI/UX Improvements (design, navigation)
        - Settings & Preferences
        - Data Import/Export
        - Performance & Optimization
        - Accessibility
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority Level
      description: How important is this feature to you?
      options:
        - Low (nice to have)
        - Medium (would improve my experience)
        - High (significantly impacts my usage)
        - Critical (prevents me from using the app effectively)
    validations:
      required: true

  - type: textarea
    id: user-story
    attributes:
      label: User Story
      description: Describe this feature as a user story
      placeholder: "As a [type of user], I want [feature] so that [benefit/goal]"
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the feature request here
      placeholder: Any additional information...