name: Publication

on:
  workflow_dispatch:
  workflow_run:
    workflows: [ "Build & Test Pipeline" ]
    types:
      - completed
    branches: [ main ]

permissions:
  contents: read
  actions: read

jobs:
  eas-release:
    runs-on: ubuntu-latest
    environment: production
    if: |
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success')
    strategy:
      matrix:
        platform: [ android, ios ]
        include:
          - platform: android
            enabled: true
          - platform: ios
            enabled: false
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Setup Java (Android only)
        if: matrix.platform == 'android'
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Build for ${{ matrix.platform }}
        if: matrix.enabled
        run: npm run build:prod:${{ matrix.platform }}

      - name: Submit to store (${{ matrix.platform }})
        if: matrix.enabled && matrix.platform == 'android'
        run: npm run submit:${{ matrix.platform }}

      - name: Skip ${{ matrix.platform }} publication
        if: matrix.enabled == false
        run: echo "Skipping ${{ matrix.platform }} publication (not yet ready)"
